# Generated by Django 5.2.4 on 2025-08-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_message_options_remove_message_ad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last time the message was updated.'),
        ),
    ]
